// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub const TEST_F_32_0: f32 = 0f32;

pub const TEST_F_32_1: f32 = 1f32;

pub const TEST_F_32_9: f32 = 9f32;

pub const TEST_F_32_POS_0: f32 = 0f32;

pub const TEST_F_32_NEG_0: f32 = 0f32;

pub const TEST_F_32_POS_1: f32 = 1f32;

pub const TEST_F_32_NEG_1: f32 = -1f32;

pub const TEST_F_32_POS_9: f32 = 9f32;

pub const TEST_F_32_NEG_9: f32 = -9f32;

pub const TEST_F_64_0: f64 = 0f64;

pub const TEST_F_64_1: f64 = 1f64;

pub const TEST_F_64_9: f64 = 9f64;

pub const TEST_F_64_POS_0: f64 = 0f64;

pub const TEST_F_64_NEG_0: f64 = 0f64;

pub const TEST_F_64_POS_1: f64 = 1f64;

pub const TEST_F_64_NEG_1: f64 = -1f64;

pub const TEST_F_64_POS_9: f64 = 9f64;

pub const TEST_F_64_NEG_9: f64 = -9f64;
