// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

/// Test that one can refer to local term aliases in aliases.
pub const FOO: bool = true;

pub const BAR: bool = true;
