// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub struct SimpleArray {
    inner: Vec<u32>,
}

impl SimpleArray {
    pub fn inner(&self) -> &Vec<u32> {
        &self.inner
    }
}

impl ddl_rt::Format for SimpleArray {
    type Host = SimpleArray;
}

impl<'data> ddl_rt::ReadFormat<'data> for SimpleArray {
    fn read(reader: &mut ddl_rt::FormatReader<'data>) -> Result<SimpleArray, ddl_rt::ReadError> {
        let inner = (0..(6usize)).map(|_| Ok(reader.read::<ddl_rt::U32Be>()?)).collect::<Result<_, ddl_rt::ReadError>>()?;

        Ok(SimpleArray {
            inner,
        })
    }
}
