// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test sugared annotation style.

pub type TestU8 = fathom_runtime::U8;

pub type TestU16Le = fathom_runtime::U16Le;

pub type TestU16Be = fathom_runtime::U16Be;

pub type TestU32Le = fathom_runtime::U32Le;

pub type TestU32Be = fathom_runtime::U32Be;

pub type TestU64Le = fathom_runtime::U64Le;

pub type TestU64Be = fathom_runtime::U64Be;

pub type TestS8 = fathom_runtime::I8;

pub type TestS16Le = fathom_runtime::I16Le;

pub type TestS16Be = fathom_runtime::I16Be;

pub type TestS32Le = fathom_runtime::I32Le;

pub type TestS32Be = fathom_runtime::I32Be;

pub type TestS64Le = fathom_runtime::I64Le;

pub type TestS64Be = fathom_runtime::I64Be;

pub type TestF32Le = fathom_runtime::F32Le;

pub type TestF32Be = fathom_runtime::F32Be;

pub type TestF64Le = fathom_runtime::F64Le;

pub type TestF64Be = fathom_runtime::F64Be;
