// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

pub struct SimpleFormatArray {
    inner: Vec<u32>,
}

impl SimpleFormatArray {
    pub fn inner(&self) -> &Vec<u32> {
        &self.inner
    }
}

impl fathom_runtime::Format for SimpleFormatArray {
    type Host = SimpleFormatArray;
}

impl<'data> fathom_runtime::ReadFormat<'data> for SimpleFormatArray {
    fn read(reader: &mut fathom_runtime::FormatReader<'data>) -> Result<SimpleFormatArray, fathom_runtime::ReadError> {
        let inner = (0..(6usize)).map(|_| Ok(reader.read::<fathom_runtime::U32Be>()?)).collect::<Result<_, fathom_runtime::ReadError>>()?;

        Ok(SimpleFormatArray {
            inner,
        })
    }
}
