// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

/// Test that one can refer to local type aliases in aliases.
pub type Foo = fathom_rt::U32Be;

pub type Bar = fathom_rt::U32Be;
