// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test aliases with doc comments.

/// A 8-bit long unit of information.
pub type Byte = fathom_runtime::U8;
