// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub const FOO: bool = true;

pub fn bar() -> bool {
    if FOO { 
        true
    } else { 
        true
    }
}

pub fn baz() -> bool {
    bar()
}
