// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub const FOO: i64 = 33i64;

pub fn bar() -> bool {
    match FOO { 
        33i64 => true,
        42i64 => true,
        _ => true,
    }
}

pub fn baz() -> bool {
    bar()
}
