// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

//! Test globals.

pub type TestU8 = ddl_rt::U8;

pub type TestU16Le = ddl_rt::U16Le;

pub type TestU16Be = ddl_rt::U16Be;

pub type TestU32Le = ddl_rt::U32Le;

pub type TestU32Be = ddl_rt::U32Be;

pub type TestU64Le = ddl_rt::U64Le;

pub type TestU64Be = ddl_rt::U64Be;

pub type TestS8 = ddl_rt::I8;

pub type TestS16Le = ddl_rt::I16Le;

pub type TestS16Be = ddl_rt::I16Be;

pub type TestS32Le = ddl_rt::I32Le;

pub type TestS32Be = ddl_rt::I32Be;

pub type TestS64Le = ddl_rt::I64Le;

pub type TestS64Be = ddl_rt::I64Be;

pub type TestF32Le = ddl_rt::F32Le;

pub type TestF32Be = ddl_rt::F32Be;

pub type TestF64Le = ddl_rt::F64Le;

pub type TestF64Be = ddl_rt::F64Be;

pub type TestBool = bool;

pub type TestF32 = f32;

pub type TestF64 = f64;

pub const TEST_TRUE: bool = true;

pub const TEST_FALSE: bool = false;
