// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub struct SimpleFormatArray {
    inner: Vec<u32>,
}

impl SimpleFormatArray {
    pub fn inner(&self) -> &Vec<u32> {
        &self.inner
    }
}

impl ddl_rt::Format for SimpleFormatArray {
    type Host = SimpleFormatArray;
}

impl<'data> ddl_rt::ReadFormat<'data> for SimpleFormatArray {
    fn read(reader: &mut ddl_rt::FormatReader<'data>) -> Result<SimpleFormatArray, ddl_rt::ReadError> {
        let inner = (0..(6usize)).map(|_| Ok(reader.read::<ddl_rt::U32Be>()?)).collect::<Result<_, ddl_rt::ReadError>>()?;

        Ok(SimpleFormatArray {
            inner,
        })
    }
}
