// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

#[derive(Copy, Clone)]
pub struct Pair {
    first: u8,
    second: u8,
}

impl Pair {
    pub fn first(&self) -> u8 {
        self.first
    }

    pub fn second(&self) -> u8 {
        self.second
    }
}

impl ddl_rt::Format for Pair {
    type Host = Pair;
}

impl<'data> ddl_rt::ReadFormat<'data> for Pair {
    fn read(ctxt: &mut ddl_rt::ReadCtxt<'data>) -> Result<Pair, ddl_rt::ReadError> {
        let first = ctxt.read::<ddl_rt::U8>()?;
        let second = ctxt.read::<ddl_rt::U8>()?;

        Ok(Pair {
            first,
            second,
        })
    }
}
