// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub struct Foo {
    pub field_type: ddl_rt::InvalidDataDescription,
    pub field_true: ddl_rt::InvalidDataDescription,
    pub field_false: ddl_rt::InvalidDataDescription,
}

impl ddl_rt::Binary for Foo {
    type Host = Foo;
}

impl<'data> ddl_rt::ReadBinary<'data> for Foo {
    fn read(ctxt: &mut ddl_rt::ReadCtxt<'data>) -> Result<Foo, ddl_rt::ReadError> {
        let field_type = ctxt.read::<ddl_rt::InvalidDataDescription>()?;
        let field_true = ctxt.read::<ddl_rt::InvalidDataDescription>()?;
        let field_false = ctxt.read::<ddl_rt::InvalidDataDescription>()?;

        Ok(Foo {
            field_type,
            field_true,
            field_false,
        })
    }
}
