// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

#[derive(Copy, Clone)]
pub struct Pair {
    first: ddl_rt::InvalidDataDescription,
    second: ddl_rt::InvalidDataDescription,
}

impl Pair {
    pub fn first(&self) -> ddl_rt::InvalidDataDescription {
        self.first
    }

    pub fn second(&self) -> ddl_rt::InvalidDataDescription {
        self.second
    }
}

impl ddl_rt::Format for Pair {
    type Host = Pair;
}

impl<'data> ddl_rt::ReadFormat<'data> for Pair {
    fn read(reader: &mut ddl_rt::FormatReader<'data>) -> Result<Pair, ddl_rt::ReadError> {
        let first = reader.read::<ddl_rt::InvalidDataDescription>()?;
        let second = reader.read::<ddl_rt::InvalidDataDescription>()?;

        Ok(Pair {
            first,
            second,
        })
    }
}
