// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test that a struct with a host type field produces a warning.

#[derive(Copy, Clone)]
pub struct Test {
    format: u32,
    host: fathom_runtime::InvalidDataDescription,
}

impl Test {
    pub fn format(&self) -> u32 {
        self.format
    }

    pub fn host(&self) -> fathom_runtime::InvalidDataDescription {
        self.host
    }
}

impl fathom_runtime::Format for Test {
    type Host = Test;
}

impl<'data> fathom_runtime::ReadFormat<'data> for Test {
    fn read(reader: &mut fathom_runtime::FormatReader<'data>) -> Result<Test, fathom_runtime::ReadError> {
        let format = reader.read::<fathom_runtime::U32Be>()?;
        let host = reader.read::<fathom_runtime::InvalidDataDescription>()?;

        Ok(Test {
            format,
            host,
        })
    }
}
