// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

pub const IS_BE: bool = true;

pub type Bar = fathom_runtime::F32Be;

#[derive(Copy, Clone)]
pub struct Test {
    bar: f32,
}

impl Test {
    pub fn bar(&self) -> f32 {
        self.bar
    }
}

impl fathom_runtime::Format for Test {
    type Host = Test;
}

impl<'data> fathom_runtime::ReadFormat<'data> for Test {
    fn read(reader: &mut fathom_runtime::FormatReader<'data>) -> Result<Test, fathom_runtime::ReadError> {
        let bar = reader.read::<fathom_runtime::F32Be>()?;

        Ok(Test {
            bar,
        })
    }
}
