// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test a pair struct.

/// A pair of bytes.
#[derive(Copy, Clone)]
pub struct Pair {
    first: u8,
    second: i8,
}

impl Pair {
    /// The first field.
    pub fn first(&self) -> u8 {
        self.first
    }

    /// The second field.
    pub fn second(&self) -> i8 {
        self.second
    }
}

impl fathom_rt::Format for Pair {
    type Host = Pair;
}

impl<'data> fathom_rt::ReadFormat<'data> for Pair {
    fn read(reader: &mut fathom_rt::FormatReader<'data>) -> Result<Pair, fathom_rt::ReadError> {
        let first = reader.read::<fathom_rt::U8>()?;
        let second = reader.read::<fathom_rt::I8>()?;

        Ok(Pair {
            first,
            second,
        })
    }
}
