// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test an empty struct.

#[derive(Copy, Clone)]
pub struct Empty {}

impl fathom_rt::Format for Empty {
    type Host = Empty;
}

impl<'data> fathom_rt::ReadFormat<'data> for Empty {
    fn read(_: &mut fathom_rt::FormatReader<'data>) -> Result<Empty, fathom_rt::ReadError> {
        Ok(Empty {})
    }
}
