// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

//! Test that a struct with a host type field produces a warning.

#[derive(Copy, Clone)]
pub struct Test {
    format: u32,
    host: fathom_rt::InvalidDataDescription,
}

impl Test {
    pub fn format(&self) -> u32 {
        self.format
    }

    pub fn host(&self) -> fathom_rt::InvalidDataDescription {
        self.host
    }
}

impl fathom_rt::Format for Test {
    type Host = Test;
}

impl<'data> fathom_rt::ReadFormat<'data> for Test {
    fn read(reader: &mut fathom_rt::FormatReader<'data>) -> Result<Test, fathom_rt::ReadError> {
        let format = reader.read::<fathom_rt::U32Be>()?;
        let host = reader.read::<fathom_rt::InvalidDataDescription>()?;

        Ok(Test {
            format,
            host,
        })
    }
}
