// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

//! Test a singleton struct.

#[derive(Copy, Clone)]
pub struct Byte {
    inner: u8,
}

impl Byte {
    pub fn inner(&self) -> u8 {
        self.inner
    }
}

impl ddl_rt::Format for Byte {
    type Host = Byte;
}

impl<'data> ddl_rt::ReadFormat<'data> for Byte {
    fn read(ctxt: &mut ddl_rt::ReadCtxt<'data>) -> Result<Byte, ddl_rt::ReadError> {
        let inner = ctxt.read::<ddl_rt::U8>()?;

        Ok(Byte {
            inner,
        })
    }
}
