// This file is automatically @generated by fathom 0.1.0
// It is not intended for manual editing.

pub const IS_BE: bool = true;

#[derive(Copy, Clone)]
pub struct Test {
    bar: f32,
}

impl Test {
    pub fn bar(&self) -> f32 {
        self.bar
    }
}

impl fathom_rt::Format for Test {
    type Host = Test;
}

impl<'data> fathom_rt::ReadFormat<'data> for Test {
    fn read(reader: &mut fathom_rt::FormatReader<'data>) -> Result<Test, fathom_rt::ReadError> {
        let bar = reader.read::<fathom_rt::F32Be>()?;

        Ok(Test {
            bar,
        })
    }
}
