use codespan_reporting::Diagnostic;
use std::io;
use std::io::prelude::*;

use crate::core;

pub fn compile_module(
    writer: &mut impl Write,
    module: &core::Module,
) -> io::Result<Vec<Diagnostic>> {
    let diagnostics = Vec::new();

    let pkg_name = env!("CARGO_PKG_NAME");
    let pkg_version = env!("CARGO_PKG_VERSION");

    writeln!(
        writer,
        "// This file is automatically @generated by {} {}",
        pkg_name, pkg_version,
    )?;
    writeln!(writer, "// It is not intended for manual editing.")?;

    for item in &module.items {
        match item {
            core::Item::Struct { doc, name, .. } => {
                writeln!(writer)?;
                for doc_line in doc.lines() {
                    match doc_line {
                        line if line.trim().is_empty() => writeln!(writer, "///")?,
                        line => writeln!(writer, "/// {}", line)?,
                    }
                }
                writeln!(writer, "pub struct {} {{}}", name)?;
            }
        }
    }

    Ok(diagnostics)
}
