// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

/// A pair of bytes.
pub struct Pair {
    /// The first field.
    pub first: u8,
    /// The second field.
    pub second: u8,
}
