// This file is automatically @generated by ddl 0.1.0
// It is not intended for manual editing.

pub struct Pair {
    pub first: ddl_rt::InvalidDataDescription,
    pub second: ddl_rt::InvalidDataDescription,
}
